# Generated by Django 5.0.6 on 2024-06-15 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authenticationapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Authentication',
        ),
    ]
